dist: trusty
language: node_js
node_js:
  - "10"

cache:
  - npm
  - agent/node_modules
  - app/node_modules
  - $(npm config get prefix)/lib/node_modules

before_install:
  - "npm i -g cross-env codecov"
  - docker pull keymetrics/pm2:10-jessie

install:
  - cd agent && npm install
  - cd ../
  - cd app && npm install
  - cd ../

script:
  - cd agent && npm run travis-test
  - cd ../
  - cd app && npm run travis-test
  - cd ../
  - cd agent && ./build-image.sh
  - cd ../
  - cd app && ./build-image.sh
  - cd ../